# Base16 Division - kitty color config
# by typedivision (https://github.com/typedivision/division/blob/master/division.yml)

background #21201e
foreground #fbffff
selection_background #fbffff
selection_foreground #21201e
url_color #bdae93
cursor #fbffff
active_border_color #bc404e
inactive_border_color #fadc68
active_tab_background #21201e
active_tab_foreground #fbffff
inactive_tab_background #fadc68
inactive_tab_foreground #bdae93
tab_bar_background #fadc68

# normal
color0 #21201e
color1 #292929
color2 #383838
color3 #585858
color4 #b6b8b8
color5 #d6d8d8 
color6 #e6e8e8
color7 #fbffff

# bright
color8 #bc404e
color9 #dc965f
color10 #fadc68
color11 #96be0e
color12 #bdae93
color13 #389ED5
color14 #b295f0
color15 #a16946
