# prefix
unbind-key C-b
set -g prefix C-t
bind-key C-t send-prefix

# status bar styles
set-option -g status-style bg=default

# fuzzy file finder (fzf)
# set -g @plugin 'sainnhe/tmux-fzf'

# window management (like chrome tabs)
unbind-key c
bind t new-window
bind w kill-window

# window navigation
bind-key -n C-t-] next-window
bind-key -n C-t-[ previous-window

# panes management
bind | split-window -h
bind _ split-window -v

# panes navigation (like vim)
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R
bind-key -n C-j select-pane -D
bind-key -n C-h select-pane -L
